role_required helper

diff --git a/shared/role_helper b/shared/role_helper
--- a/shared/role_helper
+++ b/shared/role_helper
@@ -6,6 +6,7 @@
 
 # init_d_refresh - start init.d script if not started, else force-reload
 # package_installed - apt-get install only if not installed
+# role_required - fails unless role given as argument is installed
 # run_file_as_user - runs executable as other user, fixing file permissions
 # save_heredoc_in - puts heredoc into file and adds file to tracking list
 # track_path - adds file to tracking list
@@ -55,6 +56,18 @@ package_installed() {
   do
     dpkg --status ${package_name} >/dev/null || apt-get install ${package_name}
   done
+}
+
+role_required() {
+  local role_name=${1}
+  local role_path="${TOGGL_ROLES_PATH}/${role_name}"
+
+ if [ -f "${role_path}" ]; then
+   echo "Role ${role_name} $(cat ${role_path}) detected"
+ else
+   >&2 echo "Role ${role_name} must be installed first"
+   exit 10
+ fi
 }
 
 run_file_as_user(){
